# Site settings
title: Katrina VA
tagline: By Pixelarity
description: > # this means to ignore newlines until "baseurl:"
  Katrina is a professional American female voice actor and will voice anything from advertisements, videos, animation, e-learning, to IVR and anything your project needs. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Collections
# Add new slides as HTML files inside the _reel folder
collections:
  - reel